### ISSUE TITLE
无法设置

### ISSUE THREAD

**Issue by ChuGary** [nonwill/goldendict#13]
无法自定义词典目录，没看到这个content文件夹，也无法修改

**Comment by ChuGary** [comment]
![image](https://user-images.githubusercontent.com/60617720/76386112-8d9bc500-639e-11ea-8104-2921942f512e.png)
发错图了，不好意思

**Comment by ChuGary** [comment]
删除掉portable之后解决了，谢谢！

现在发现的问题是查询结果导航面板的词典条目出现得特别慢！不知道怎么解决呢？

**Comment by nonwill** [comment]
Remove portable dir
