### ISSUE TITLE
版本(版本 2A0D, jun 4 22:10) ctrl+c+c不能自动查剪贴板中的词

### ISSUE THREAD

**Issue by MrDotError** [nonwill/goldendict#15]
最新版本ctrl+c+c不能自动查剪贴板中的词，版本 2A0D, jun 4 22:10

**Comment by nonwill** [comment]
问题已复现。
原版GD中的这一功能是与取词功能绑定的 --- 仅在开启取词的情况下ctrl+c+c不剪贴板取词才会生效，在新版中需要开启取词或划词这一功能才会生效。

**Comment by MrDotError** [comment]
> 问题已复现。
> 原版GD中的这一功能是与取词功能绑定的 --- 仅在开启取词的情况下ctrl+c+c不剪贴板取词才会生效，在新版中需要开启取词或划词这一功能才会生效。

为什么我还是不行？同目录下的goldendictD.exe就可以没有开启取词的时候依旧ctrl+c +c进行查词
现在这个版本我开启取词后还是不行，前两个月的版本是没有这个问题的

**Comment by nonwill** [comment]
点击Goldendict帮助菜单 --> 配置文件夹，点击Goldendict文件菜单下的退出，删除配置文件夹下的config.nwx（剪切到其它地方备份），然后再启动Goldendict试一下呢？

**Comment by MrDotError** [comment]
> 我这两个版本（32位和64位版本）都试过了，开启划词或取词后ctrl +c+c剪切版取词是没有问题的。
> 点击Goldendict帮助菜单 --> 配置文件夹，点击Goldendict文件菜单下的退出，删除配置文件夹下的config.nwx（剪切到其它地方备份），然后再启动Goldendict试一下呢？

删除配置文件后，开启划词功能后生效了，谢谢。
