### ISSUE TITLE
最近几个版本都会出现这个病毒提示

### ISSUE THREAD

**Issue by MrDotError** [nonwill/goldendict#18]
![2020-06-28_092322](https://user-images.githubusercontent.com/65375419/85936101-710da380-b921-11ea-8e4d-4435d3c0e782.png)
win 10 自带的杀毒软件，似乎help文件的问题

**Comment by nonwill** [comment]
取词组件的问题，这个问题我在日志更新贴中有说过 --- 不确定是不是基础包中这两个程序的问题，我这也是win10，自带的杀毒软件，这两个文件是没有问题的。可以删除x64helper和x86helper程序组件，使用ocr划词取代取词功能，如果的确需要取词，**可以用官方goldendict包中的对应程序替换掉试一下**，其它的**除dll和翻译文件，如有问题也可以用官版goldendict包中对应的文件替换掉**。

**Comment by nonwill** [comment]
文件已从升级包中剔除
