### ISSUE TITLE
频繁自动结束程序

### ISSUE THREAD

**Issue by garypang13** [nonwill/goldendict#19]
在后台运行好好的,总是会自动结束程序,我每天都要启动好几次,用官方版的时候从来没遇到过.

**Comment by nonwill** [comment]
如果使用了取词，请关闭取词功能试一下。

**Comment by garypang13** [comment]
我用的是ctrl+c+c取词翻译, 取词的时候很容易发生程序闪退, 即使不通过取词,直接在程序里查词也容易发生闪退.

**Comment by nonwill** [comment]
我这测试时候400多部词典不分组都能正常查询出结果的。查词时出现闪退，多跟词典有关系 --- 或是内存分配失败（这种情况很少出现），又或者是索引问题，没有对应的词典环境，我这很难给予帮助的 --- 所以如果存在查词崩溃问题，还是要从自身情况多分析 --- 分分组吧，定位一下看是否有词典导致出问题。

**Comment by nonwill** [comment]
mdict格式词典，潜在问题太多 --- js脚本和css样式表是重灾区，遇有类似问题还请自查。
