### ISSUE TITLE
python词典导致查词时程序一定几率闪退

### ISSUE THREAD

**Issue by garypang13** [nonwill/goldendict#22]
接 https://github.com/nonwill/goldendict/issues/19 这个问题, 排查出了是某个python词典的问题,

python词典是我写的,很业余, 用于在线查询 http://www.91dict.com/words?w=test 这个网站的场景例句

可以排除和其他词典冲突,因为我把这个词典单独放一组,也会导致闪退,大概查词十来次会闪退一次,

我以前一直用的 https://sourceforge.net/projects/goldendict/files/early%20access%20builds/Qt5-based/64bit/ 这个官方版的搭配这python词典用了有两三年了从未出现过这个问题.

[yingyin.zip](https://github.com/nonwill/goldendict/files/5104886/yingyin.zip)

![image](https://user-images.githubusercontent.com/48883331/90812759-2d4f7d00-e359-11ea-8200-42ae632709ea.png)

**Comment by garypang13** [comment]
肯定是和音频播放有关,每次发生闪退,一定会有个0.2s左右的音频声音闪现,即使我取消了yingyin.py的自动播放音频,原版goldendict也有这个音频闪现的问题,但是不会导致闪退.

**Comment by nonwill** [comment]
改版支持四个音频播放引擎（外置的不算），其中原版goldendict带的ffmpeg引擎的实现最为复杂 --- 最容易出问题，换其它的音频（bass或fmodex）引擎试一下呢？

**Comment by garypang13** [comment]
音频引擎都试过了,看来还是只能换回官方版了,官方版不知道为啥不编译新版了,我自己想编译windows新版却总是失败,唉,

**Comment by nonwill** [comment]
> 音频引擎都试过了,看来还是只能换回官方版了,
> http://forum.ru-board.com/topic.cgi?forum=5&topic=49149 在这里找到了新编译的windows版, 目前使用一切正常.
> 谢谢.

官方版GoldenDict使用的时mingw编译器（mingw和gcc的版本应该也较老） --- 出于兼容性考虑，其中系统API接口的实现大都是很老的，相对来说GoldenDict运行的兼容性也比较好，只是在运行效率上运行效率上没有最新版msvc编译的高。

如果时四个引擎都会有所述问题的存在，问题应该不是出在音频播放代码上 --- 如所描述的随机崩溃前的0.2s音频闪现，大概率出在**系统**的音频处理接口内--- WIn10爆音现象我这在先前遇到过多次（包括其它音频播放器，如foobar2000播放音乐也会存在），严重时播放器或软件不退出爆音就会一直存在，经过系统和驱动更新后问题可以解决。

**Comment by garypang13** [comment]
我现在换成官方版后音频闪现问题也没出现过了,以前我用官方版是有闪现的,后来我给audio 标签加了muted属性后就没了,换成这个修改版后才又出现的闪现,我猜和webkit上应该也有点兼容性问题.

**Comment by nonwill** [comment]
> webkit上应该也有点兼容性问题

官方GoldenDict用的Webkit的版本可能是某一个稳定版 --- 至少时Qt官方曾负责的版本吧，稳定性不是问题，只是html/css/js特性支持上有欠缺。

64位改版GoldenDict用的时较新的版本源码合并到社区支持版的，支持的html/css/js特性挺多的，但到现在社区版都没能发布一个稳定版（还停在Alpha版），问题是挺多的。

32位改版的GoldenDict用的是Qt-5.9.2版本带的Webkit --- 基于Qt官方稳定版的维护版本，这个版本兼容性、稳定性和特性支持上应都还是不错的。

我没使用msvc编译过Qt-5.9.2版本带的Webkit。测下来，mingw+gcc+qtwebkit-5.9.2的运行效率（处理html/css/js的速度）很明显的**慢**于WSDK+msvc+qtwebkit-5.212.0。我个人用的是WSDK+msvc+qtwebkit-5.212.0版本的GoldenDict，在其它32位系统上用的是mingw+gcc+qtwebkit-5.9.2版的，词典少或分组比较细的话两个版本在效率上差别不大。

**Comment by nonwill** [comment]
> webkit上应该也有点兼容性问题

今天装了python开始使用，发现的确是webkit的问题。

GolenDict源码一致，WSDK+msvc+qtwebkit-5.212.0版本的GoldenDict表现描述的一样查个10几个单词吧就出现崩溃，mingw+gcc+qtwebkit-5.9.2版本的表现完美 --- 词典内容简约不失大方，很好用。

虽然WSDK+msvc+qtwebkit-5.212.0这个版本支持视频播放，但潜在的问题都不知道有多少 --- 不能追新，还是应以稳定为主。

**Comment by garypang13** [comment]
> > webkit上应该也有点兼容性问题
> 
> 今天装了python开始使用，发现的确是webkit的问题。
> 
> GolenDict源码一致，WSDK+msvc+qtwebkit-5.212.0版本的GoldenDict表现如描述的一样查个10几个单词就出现崩溃，mingw+gcc+qtwebkit-5.9.2版本的表现完美 --- 词典内容简约不失大方，很好用。
> 
> 虽然WSDK+msvc+qtwebkit-5.212.0这个版本支持视频播放，但潜在的问题不知道有多少 --- 看样子不能追新，还是应以稳定为主。

我现在用的这个是基于 Qt 5.12.3的官方版, 等您修复了这个崩溃的问题,我再换回此版本~

**Comment by nonwill** [comment]
确认是js脚本引发的这个问题（还是因为Webkit不够稳定吧），做了下简单修改 -- 对yingyin.py中的js脚本中的事件处理加了个小的延时 -- 大致是要js引擎处理完当前的事务在下一（多）个事件循环再去执行注册的事件函数吧，用了多时，没有再因此出现崩溃了。

另外那个播放前的爆音播放，是出在webkit中的 -- 即便是GoldenDict不使用任何音频播放引擎，爆音一样会播放。应该还是qtwebkit对audio标签支持的没那么好吧。


[yingyin.zip](https://github.com/nonwill/goldendict/files/5200163/yingyin.zip)

**Comment by garypang13** [comment]
谢谢, 官方版如果不加这句` $(".flex-active-slide .imgMainbox .audioa")[0].click() ` 来自动播放的话就不会出现爆音, 
或者加上 $("audio").prop("muted", false); 即:
```
setTimeout(function(){
                    $("audio").prop("muted", false);
		    $(".flex-active-slide .imgMainbox .audioa")[0].click()
},1000)
```
也不会出现爆音,
目前使用了半个月了,一切正常.
