### ISSUE TITLE
新下载的goldendict（mac版本）不能监控clipboard

### ISSUE THREAD

**Issue by TaoRuan-Campus** [nonwill/goldendict#23]
之前的老版本goldendict可以正常监控剪切板（cmd+c+c）然后取词翻译，下载的GoldenDict （macOS OCR「划词版」：GoldenDict-2020.06.16.dmg.7z）打开后cmd + c 就无法使用了 请问如何解决？

**Comment by nonwill** [comment]
抱歉，我这没有mac的机器可以测试（编译用的虚拟机环境）。但在我简单测试时，貌似剪切板、划图取词和鼠标选词操作都要得到相应的权限才可以使用 --- 可能不同的mac版本还有些许不同。

已经上传了一份较新（6月22日更新）的dmg格式的安装包，可以通过[日志主页](https://nonwill.github.io/post/goldendict/)中的百度网盘或微软云盘的地址下载，较616的版本修复了划词和取词相关的几个小问题，可以下载试一下。

**Comment by nonwill** [comment]
> cmd + c 就无法使用

感谢反馈，已查明问题所在 --- 在引入划词时候引入该问题（忽略掉了cmd+c+c热键使能的判断，影响所有平台），缺陷会在下个针对mac的编译版本中修复。当前变通的解决方法是同时选中鼠标取词或者ocr划词，cmd+c+c会同时生效。

**Comment by nonwill** [comment]
2A16-1109版本已修复。

**Comment by TaoRuan-Campus** [comment]
> 2A16-1109版本已修复。

在哪里找到这个版本

**Comment by nonwill** [comment]
> big sur系统

没big sur系统；High Sierra表现正常
