### ISSUE TITLE
GoldenDict 是否可通过扩展支持对 Firefox、Chrome 等软件的悬浮取词呢

### ISSUE THREAD

**Issue by Explorare** [nonwill/goldendict#24]
我看到这个版本的 Scan Popup 多了三个扩展，它们分别起到了什么作用呢？Firefox 和 Chrome 至今只能通过剪贴板取词，但 Windows 平板想要按出 Ctrl+C+C 并不容易。请问大佬有什么建议么？主要需求是能在 Firefox、Acrobat DC、MS Edge 里看文档时候可以触屏取词。谢谢。

**Comment by nonwill** [comment]
附加取词技术的三个选项在官版Goldendict中也是存在的（在高级页面中），能提升取词能力吧 --- 但提升有限。

这个版本（改版）中增加了原生内置ocr划词的支持，使用tesseract4 ocr识别可以获得不错的划词体验。对于原版Goldendict所带取词的不足 --- 对Firefox和Chrome浏览器及其它软件不能取词的情况，可以使用ocr划词来解决。

但划词一样需要鼠标和键盘的配合 --- 键盘按使能快捷键，取词在屏幕上划取ocr识别范围，这对平板来说都不容易完成 --- 这部分如需完善，则需要增加对触摸屏手势的支持，稍显复杂了些。

对平板上的取词来说，简单些的方法是开启自动取词和监控截切板变化选项 --- 无需快捷键就可以直接从鼠标处取词，或直接从截切板中取词翻译 --- 需要查词时，只要将浏览器或其它软件中的待查部分复制到剪切板就行。
![Uploading 20201003133205.png…]()

**Comment by Explorare** [comment]
谢谢答疑
