### ISSUE TITLE
能否增加下百度OCR等在线接口？

### ISSUE THREAD

**Issue by EsuRt** [nonwill/goldendict#25]
自带的两个OCR引擎对手写等部分文本的识别率不是很高，能否增加下百度OCR、腾讯OCR等接口，在线OCR的识别率目前还不错，可自己申请后使用。另外，截图识别时，能否加个选择OCR引擎的功能？不同引擎的识别率有所却区别，方便识别错误时快速进行切换。

**Comment by nonwill** [comment]
个人需求的个性化插件是可以自由开发添加的，当前ocr插件接口已基本定型，如有需要可Email我，可以提供相关SDK。
