### ISSUE TITLE
Failed to get GrabAndOcr Helper

### ISSUE THREAD

**Issue by Explorare** [nonwill/goldendict#26]
环境：Windows 2004 x64
版本：2A14 x64
最近更近之后启动 GoldenDict 进程之后会弹出这个错误信息，应该和最近 OCR 功能独立成插件有关？我该如何配置呢？谢谢。

**Comment by nonwill** [comment]
重新配置一下ocr参数就可以了，如下图：
![20201022213323](https://user-images.githubusercontent.com/46510529/96879206-52be4b80-14ae-11eb-8eda-d19dc24eef43.png)
