### ISSUE TITLE
Win10系统Goldendict OCR版本无法添加在线词典

### ISSUE THREAD

**Issue by Sunny-27** [nonwill/goldendict#29]
一旦添加就崩溃。。。

**Comment by nonwill** [comment]
>[2020.10.21 2A14：内存使用和查询效率相关的一些优化；通过传递屏幕dpi参数值来提高ocr识别的精度；**修正在词典编辑对话框，编辑词典（增加或删除词典操作）后，点击OK按钮导致程序崩溃的问题**](https://nonwill.github.io/post/goldendict/#20201024-2a1564%E4%BD%8Dmsvc%E7%89%88%E6%9C%AC%E5%9B%9E%E9%80%80%E4%BD%BF%E7%94%A8qt-599%E8%AF%A5%E7%89%88%E6%9C%AC%E7%95%8C%E9%9D%A2%E5%B7%A5%E5%85%B7%E6%A0%8F%E6%97%A0%E4%B8%8D%E5%8F%AF%E9%80%86%E7%9A%84%E5%86%85%E5%AD%98%E6%B3%84%E9%9C%B2%E4%BF%AE%E6%AD%A3dictionarybar%E7%9A%84%E5%86%85%E5%AD%98%E6%B3%84%E9%9C%B2mingwgcc%E7%89%88%E5%AE%8C%E5%85%A8%E6%9C%89%E6%95%88qt-512%E5%92%8Cqt-515%E7%9A%84msvc%E7%89%88%E6%9C%AC%E8%BF%98%E6%98%AF%E6%9C%89%E9%83%A8%E5%88%86%E6%B3%84%E9%9C%B2-----%E6%98%AF%E5%90%A6qt%E9%97%AE%E9%A2%98%E6%9C%89%E5%BE%85%E5%AE%98%E6%96%B9%E5%8F%8D%E9%A6%88)。

感谢反馈。如果问题如上所述，请等待下一个发版更新编译后上传。如果不是上述问题，还请详述一下版本和还原过程。

**Comment by nonwill** [comment]
[2A15已更新](https://nonwill.github.io/post/goldendict/#20201026-2a15%E9%80%82%E9%85%8Dqt4-----%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85%E5%BE%AE%E8%BD%AF%E7%9A%84%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BA%93httpsakamsvs16releasevc_redistx86exe%E5%8D%87%E7%BA%A7%E5%8C%85%E5%8D%B3%E4%B8%BA%E6%95%B4%E5%8C%85%E8%A7%A3%E5%8E%8B%E5%8D%B3%E5%8F%AF%E4%BD%BF%E7%94%A8)

**Comment by Sunny-27** [comment]
GoldenDict-Qt-4.8.7-msvc-16.7.6-x86-20201026.7z<https://github.com/nonwill/nwDeployed/releases/download/GoldenDict_OCR_2A15_20201026/qt4_x86_msvc.tar.bz2>  新版开启OCR软件崩溃

________________________________
发件人: nonwill <notifications@github.com>
发送时间: 2020年10月26日 12:20
收件人: nonwill/goldendict <goldendict@noreply.github.com>
抄送: Sunny-27 <guiguitupaopao@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [nonwill/goldendict] Win10系 统Goldendict OCR版本无法添加在线词典 (#29)


2A15已更新<https://nonwill.github.io/post/goldendict/#20201026-2a15%E9%80%82%E9%85%8Dqt4-----%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85%E5%BE%AE%E8%BD%AF%E7%9A%84%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BA%93httpsakamsvs16releasevc_redistx86exe%E5%8D%87%E7%BA%A7%E5%8C%85%E5%8D%B3%E4%B8%BA%E6%95%B4%E5%8C%85%E8%A7%A3%E5%8E%8B%E5%8D%B3%E5%8F%AF%E4%BD%BF%E7%94%A8>

―

**Comment by nonwill** [comment]
> GoldenDict-Qt-4.8.7-msvc-16.7.6-x86

这个是32位版本全包，请不要与任何64位版本混用且不兼容官方版本，首次发布，不要从任何其它版本升级。
关于ocr，请参考https://github.com/nonwill/goldendict/issues/26 重新设置一下，关键的是要选对识别库目录，也就是里面截图所示的目录。

**Comment by nonwill** [comment]
> Qt-4.8.7-msvc-16.7.6-x86

已更新，解决了改版中存有的一些问题。
