### ISSUE TITLE
不能添加词典。选项是灰色的？？

### ISSUE THREAD

**Issue by TianMo-ZhangSan** [nonwill/goldendict#30]
打开词典选项，添加和删除都是灰色。
下的是GoldenDict-Qt-5.9.9-msvc-16.7.6-x64-20201031
win10 x64

**Comment by TianMo-ZhangSan** [comment]
> 打开词典选项，添加和删除都是灰色。
> 下的是GoldenDict-Qt-5.9.9-msvc-16.7.6-x64-20201031
> win10 x64

**Comment by chenw191** [comment]
请问一下是怎么解决的呢？我貌似遇到了类似的问题

**Comment by TianMo-ZhangSan** [comment]
删除portable文件夹

chenw191 <notifications@github.com> 于 2020年11月1日周日 上午10:49写道：
