### ISSUE TITLE
最新版本goldendict与有道词典冲突

### ISSUE THREAD

**Issue by bahuwang** [nonwill/goldendict#31]
如果同时使用goldendict与有道词典，当用有道词典取词是，所选取内容直接变成 c 。

例如：内容如下，
responsibility falls 取词前
c falls                    点击有道图标，取词后

**Comment by nonwill** [comment]
关掉任何一个软件的取词 --- 其实我个人来讲，压根儿不推荐开启取词 --- 除非绝对信任这个或那个软件。
