### ISSUE TITLE
Failed to get GrabAndOCR Helper

### ISSUE THREAD

**Issue by elmarlee** [nonwill/goldendict#33]
感谢分享，比原版好用多了！我刚更新成了qt5_x64_msvc "2A16 周六 10月31日 02:17:20 2020"。打开OCR/Nicomsoft之后，会报一个错“Failed to get GrabAndOCR Helper”, OCR取词的十字光标也不能出现。这是因为GitHub里缺文件吗？

**Comment by nonwill** [comment]
Reder to https://github.com/nonwill/goldendict/issues/26

**Comment by elmarlee** [comment]
Yes, it worked very well for me. Thanks for your reply.
