### ISSUE TITLE
词典内双击或者通过链接查词跳转的问题

### ISSUE THREAD

**Issue by smilyhe** [nonwill/goldendict#34]
平台：MacOS 10.15.6
版本：1.5.0 2A0F

在词典内双击或者通过链接查词，目前的行为是跳转到双击发生的那部词典。比如：有20部词典，在第10部词典内双击一个单词，于是会查询该单词，并且直接跳转到第10部词典。在某些情况下，这不太方便。比如某部字典列举了很多同根词，或者同义词，用户点击是希望查看词义。通常来说，用户会把常用的词典放在开头。所以默认的行为查询新词的时候跳转到开头第一部词典更为合适。大多数词典的行为也是这样的。当然，这可能并不能算一个bug，但不知道是否能提供一个设置，又或者有办法可以改变这种行为。谢谢。

**Comment by nonwill** [comment]
>查询新词的时候跳转到开头第一部词典

2A0F是与官方版本兼容的最后一个版本，已不做维护。
建议升级到最新的2A16版并开启 阅读模式，该模式下，按住Ctrl 然后双击或通过链接查词，可以通过pop窗口进行，并且使用联合分组查词，是可以满足以上需求的。
![20201108221435](https://user-images.githubusercontent.com/46510529/98467462-68eb3c00-2210-11eb-965b-00b6f387623a.png)
