### ISSUE TITLE
"version `Qt_5.15' not found" Error when Running on Manjaro 20.2 with KDE Plasma

### ISSUE THREAD

**Issue by walwan** [nonwill/goldendict#36]
# Error Message
- Commands execuated:
```shell
tar -xzvf GoldenDict-OCR-ubuntu-20.04-x64-20201105.tar.gz
cd goldendict_qt5_x64_linux
./goldendict
```
- Output:
```shell
./GoldenDict: /home/XXXX/GoldenDict/goldendict_qt5_x64_linux/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/libQt5TextToSpeech.so.5)
```

# Environment
- `lsb_release -a`
```shell
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2
Codename:       Nibia
```
- `uname -a`
```shell
Linux Satellite 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux
```

# Other information
- I already have a qt running environment installed on my computer.
- I tried to output the $LD_LIBRARY_PATH and the $PATH before the start of Goldendict
```shell
/home/XXXX/GoldenDict/goldendict_qt5_x64_linux/lib:
/home/XXXX/GoldenDict/goldendict_qt5_x64_linux:/home/XXXX/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
```

**Comment by nonwill** [comment]
Sorry, my bad. libQt5TextToSpeech.so is not packed into GoldenDict-OCR-ubuntu-20.04-x64-20201105.tar.gz. I'll update it later.

**Comment by nonwill** [comment]
Package is updated with all Qt dependences. Extra basic libs were also added which may be not needed(if there any errors, just delete them):
`libX11.so.6
libpthread.so.0
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
libxcb.so.1
libdl.so.2
libz.so.1
libgio-2.0.so.0
libgobject-2.0.so.0
libglib-2.0.so.0
librt.so.1
libGL.so.1
libharfbuzz.so.0
libresolv.so.2
libGLdispatch.so.0
libGLX.so.0
libfreetype.so.6
`

**Comment by walwan** [comment]
Thanks!
Actually, I have to remove these "Extra basic libs" if I want to run it on my system. 

> Package is updated with all Qt dependences：https://github.com/nonwill/nwDeployed/releases/download/GoldenDict%2B%2BOCR_2A16_20201111/GoldenDict-OCR-ubuntu-20.04-x64-20201105-1.tar.gz
> Extra basic libs were also added which may not be needed(if there are any errors, just delete them):
> `libX11.so.6 libpthread.so.0 libstdc++.so.6 libm.so.6 libgcc_s.so.1 libc.so.6 libxcb.so.1 libdl.so.2 libz.so.1 libgio-2.0.so.0 libgobject-2.0.so.0 libglib-2.0.so.0 librt.so.1 libGL.so.1 libharfbuzz.so.0 libresolv.so.2 libGLdispatch.so.0 libGLX.so.0 libfreetype.so.6 `
