### ISSUE TITLE
Missing source code and misleading GoldenDict Wiki modifications

### ISSUE THREAD

**Issue by vedgy** [nonwill/goldendict#37]
Hi @nonwill!

1. Whenever a binary version of GoldenDict is published, the sources used to build it must be published too. Not doing so is a violation of the GPL. The [supplied link](https://github.com/nonwill/goldendict/commits/master) is no longer valid.

2. The recently added **++OCR personal build** sections on the three **Early Access Builds** pages of [the official GoldenDict wiki](https://github.com/goldendict/goldendict/wiki) are misleading. For years, only builds prepared by GoldenDict maintainers were linked to from these pages. I think that this should stay this way, unless you have obtained a permission to post links to your modified GoldenDict version on these pages from GoldenDict maintainers. Have you? If not, please obtain the permission or remove the links. One problem is that most GoldenDict users probably have more reason to trust long-time GoldenDict maintainers than you. Another problem is that if a user is mislead into thinking that he/she is running an official GoldenDict version, he/she might create issues on the official GoldenDict issue tracker, even if they are actually regressions in your modified version. I think that your [dedicated Wiki page](https://github.com/goldendict/goldendict/wiki/GoldenDict%E2%88%9EOCR-Release-Builds-for-macOS,-Ubuntu-and-Windows) is sufficient to promote your fork.

**Comment by nonwill** [comment]
Sorry for the confusion. I've reverted all changes I made on the Official Wiki pages and If possible please help me to remove the permission that I was able to edit&post pages there, thanks.

**Comment by vedgy** [comment]
1. This issue still remains: wherever you publish the binaries, even on [your own site](https://nonwill.github.io/post/goldendict), the source code must be available to comply with the GPL. In all places where you post links to binaries, please provide a link to the source code, from which they were built.

2. If you make the source code available again, you can restore your separate and dedicated Wiki page on the official GoldenDict Wiki (**GoldenDict∞OCR Release Builds for macOS, Ubuntu and Windows**). This page was sufficiently unobtrusive. Just make sure that it states clearly that the builds are unofficial and based on your fork.

>  if possible please help me to remove the permission that I was able to edit&post pages there

There is no problem in editing and posting on the official GoldenDict Wiki per se. That's the spirit of the Wiki technology. There are many useful contributions from non-maintainers in the GoldenDict Wiki. The problem was in placing links to builds of a fork on the highly visible and security-sensitive pages where official builds have been posted for years. Restricting edits to these 3 pages would make sense, but unfortunately it seems that GitHub doesn't allow assigning permissions to individual Wiki pages.

**Comment by nonwill** [comment]
>please provide a link to the source code, from which they were built.

Sorry for that. I've commited a pull-request to official repo before, but I closed it recently, because it seems like that it'll never be accepted. The latest codes I work on are far away from and Not Compatible with official ones and in the future, I will try to keep the distribution binary for a small group of individuals.
